name: pharmassist-pro
services:
- name: frontend
  source_dir: /frontend
  github:
    repo: your-username/pharmassist-pro
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: REACT_APP_API_URL
    value: ${backend.PUBLIC_URL}

- name: backend
  source_dir: /backend
  github:
    repo: your-username/pharmassist-pro
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  - path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"